services:
  minuto90-backend:
    container_name: minuto90-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4500:4500"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
